# XPAIO 공식 구성 파일
NETWORK_PASSPHRASE="Pi Testnet"

[[CURRENCIES]]
code="XPAIO"
issuer="GDMHOZS5A6QZFI55WMGLZRAJMYUC5WEEMCEYY6JS5WVTTSGK4XLZQUVR"
display_decimals=2
name="XPAIO Team"
desc="Official utility token for the XPAIO ecosystem."
image="https://cool-entremet-699764.netlify.app/icon.png"

[METADATA]
# 파이 개발자 포털 유효성 검증 키
VERIFICATION_KEY="8269c9f9a9148a21ae8a7b675f369c9f23c15ef995adfd7a77b12b6d280b9703f4a9eb19a120e099a1df263cf2de107b3cef91355219a1d3ca37225dcb4954c0"